name: 'Event Data Updater'
run-name: Event Data Update
on:
  workflow_dispatch:
  schedule:
    # Run every Wednesday at 08:00 UTC (during weekly maintenance)
    - cron: '0 8 * * 3'
jobs:
  Update-Event-Data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Configure date
        run: |
          echo "ACTION_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
      - name: Pull Remote Changes
        run: |
          git pull
      - run: |
          python src/auto_scraper.py
      - name: Commit changes to data
        uses: stefanzweifel/git-auto-commit-action@v5
        with: 
          file_pattern: 'data/*.json'
          commit_message: "data: event update ${{env.ACTION_DATE}}"
