name: 'Auto collect data'
run-name: Auto-collecting Event Data
on:
  schedule:
    # Run every Wednesday at 09:00 UTC (during weekly maintenance)
    - cron: 0 9 * * 3
jobs:
  Scrape-Event-Data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps: 
      - uses: actions/checkout@v3
      - name: Configure date
        run: |
          echo "ACTION_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
      - name: Gather Event Data
        run: node ./bin/actions.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: "Event data update: ${{env.ACTION_DATE}}"
      - run: echo "This job's status is ${{ job.status }}"
